### ISSUE TITLE
Usage with pgtyped (i. e. typed tagged templates)

### ISSUE THREAD

**Issue by arnold-graf** [frigus02/vscode-sql-tagged-template-literals#10]
Hi!

First off: thanks for making this awesome plugin.

I’ve been trying to use it in a setup with the [pgtyped](https://github.com/adelsz/pgtyped) to automatically generate types from queries, which requires explicitly spelling out a type name for a query.

However the parser doesn’t seem to recognize queries in _typed_ tagged template literals, as in Line 4:
```TypeScript
import { sql } from '@pgtyped/query'
import { ISelectTableRows } from './index.queries.ts'
import { Client } from 'pg'
const query = sql<ISelectTableRows>`SELECT * FROM table`
const result = await query.run(void(0), Client);
```
Again, thanks for your publishing this tool, and best wishes!

**Comment by frigus02** [comment]
Hi. Thanks for reporting. I agree that this should work.

I have to admit, I struggled a bit to get the grammar working for #7. I'm not super confident, that I can make this work. But I'm happy to give it a go 🙂.

**Comment by frigus02** [comment]
Okay, that wasn't as tricky as I thought. Uploaded version 0.0.14, which should support that. 🤞

**Comment by arnold-graf** [comment]
It worked! Thanks!
