### ISSUE TITLE
Thanks for this!!

### ISSUE THREAD

**Issue by karlhorky** [frigus02/vscode-sql-tagged-template-literals#13]
Hi there, sorry for the issue noise, but I just wanted to open this to thank you!

This library is super helpful for our students at @upleveled, to show them when they have added one comma too many in the syntax (or passed in the wrong type). Very awesome, kudos! 🙌

Will close this again now :)

**Comment by frigus02** [comment]
Thanks Karl. This is the best kind of feedback 😊
