### ISSUE TITLE
Svelte support

### ISSUE THREAD

**Issue by hmt** [frigus02/vscode-sql-tagged-template-literals#15]
Looks very nice! Thank you.

Could you please add support for svelte files? source.svelte should do as it is the only extension in place right now.

**Comment by frigus02** [comment]
Yep, you're right. Adding source.svelte seems to do the trick. Seems like a good idea to add that.

**Comment by frigus02** [comment]
I just pushed a new version of the syntax extension with support for Svelte files.

**Comment by hmt** [comment]
Very nice, thank you. You may want to add .vue as well. Not using it but they have single file components too.
