### ISSUE TITLE
Incorrect syntax highlighting when using `sql` as a regular function

### ISSUE THREAD

**Issue by PaulKiddle** [frigus02/vscode-sql-tagged-template-literals#16]
Some libraries, like [postgres](https://www.npmjs.com/package/postgres), allow their template function to [also be called as a regular function](https://www.npmjs.com/package/postgres#dynamic-query-helpers-sql-inside-tagged-template).

When doing this, code following the `sql` function call no longer has correct syntax highlighting.

Illustrative example:

![Screenshot from 2021-01-11 14-36-36](https://user-images.githubusercontent.com/1755184/104195479-9758e380-541a-11eb-9ccd-a5c098fa5276.png)

Slightly more realistic example - 
here the `return` keyword should be purple, not white:

![Screenshot from 2021-01-11 14-46-12](https://user-images.githubusercontent.com/1755184/104196531-cb80d400-541b-11eb-971f-c26fff11d69a.png)

**Comment by frigus02** [comment]
Oh no. Thanks for reporting. Just for completeness, which version of VS Code are you using?

I'm probably going to have a look at this on Friday. Happy to review and test a PR if you can get to it before then.

**Comment by PaulKiddle** [comment]
Thanks, I'm using 1.52.1 (VSCodium build, if that makes a difference). I'm afraid I don't have time at the moment to submit a PR, but anyway I'm not in any rush for a fix since it's only a cosmetic issue.

**Comment by frigus02** [comment]
I pushed a new version of the extension, which fixes the issue for me. Please let me know if this didn't fix it for you.

**Comment by PaulKiddle** [comment]
Working fine now, thanks very much!
