### ISSUE TITLE
`SQL` (uppercase) should be equal to `sql`

### ISSUE THREAD

**Issue by codeclown** [frigus02/vscode-sql-tagged-template-literals#17]
I think also uppercase `SQL` should be supported. See the difference:

![image](https://user-images.githubusercontent.com/211543/106929817-7e8fd500-671d-11eb-8c06-f3e2c1e817f6.png)

E.g. [`node-sql-template-strings`](https://github.com/felixfbecker/node-sql-template-strings) uses uppercase in their examples:

> Example for escaping queries (callbacks omitted):
> ```js
> mysql.query(SQL`SELECT author FROM books WHERE name = ${book} AND author = ${author}`)
> ```

**Comment by frigus02** [comment]
Good point. I don't see a reason to make case sensitively. May as well support `sql`, `Sql`, `SQL` or even `sQl`.

**Comment by frigus02** [comment]
I uploaded a new version. Should be available in the next minutes.

**Comment by codeclown** [comment]
Nice, thanks!
