### ISSUE TITLE
Support for private class field accessors

### ISSUE THREAD

**Issue by PaulKiddle** [frigus02/vscode-sql-tagged-template-literals#18]
Thanks again for this extension.

I'd like to request support of highlighting for `this.#sql` usage:

```javascript
export default class Config {
  #sql;
  constructor(execSql){
    this.#sql = execSql;
  }
  async get(key){
    const [{value}] = this.#sql`SELECT value FROM config WHERE key=${key}`;
    return value;
  }
}
```

I had a little look to see if I could contribute but the regex looks pretty complicated

**Comment by frigus02** [comment]
Hi Paul. Supporting private fields/functions sounds like a good idea. And yeah, the regex is horrendous 😅. It's copied from [TypeScript.tmLanguage.json](https://github.com/microsoft/vscode/blob/74623bc93c5482cbf6fbb78346167cb39717b703/extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json). But this gets updated continuously and I didn't copy all the different possible cases, yet, I believe.

I created [this script](https://github.com/frigus02/vscode-sql-tagged-template-literals/blob/main/regex-help.mjs) recently, which breaks a regex into separate lines and indents brackets to make them a bit easier to read. It's not documented, yet. But here's the gist:

- Create a file and paste a regex into it. Paste the entire string including quotes. It's going to be parsed as a JSON string. Then run

  ```
  node regex-help.mjs prettify file-to-file-with-regex.json > pretty-regex.txt
  ```

- You can then edit the regex and turn it back into a JSON string with:

  ```
  node regex-help.mjs minify pretty-regex.txt > file-to-file-with-regex.json
  ```

I should find some time to look into this end of next week as well.

**Comment by frigus02** [comment]
I uploaded a new version, which should fix the problem. Should be available for download in the next minutes.
