### ISSUE TITLE
Unable to use dynamic table name in query

### ISSUE THREAD

**Issue by pm0u** [frigus02/vscode-sql-tagged-template-literals#34]
Attempting to use a dynamic table name throws a syntax error

```ts
const table = 'table'
sql`select * from ${table}`
```

<img width="616" alt="image" src="https://github.com/frigus02/vscode-sql-tagged-template-literals/assets/410558/47fafd27-9a11-4581-997f-bbd3ac1455ee">

**Comment by frigus02** [comment]
I think you might want the syntax-only extension: https://marketplace.visualstudio.com/items?itemName=frigus02.vscode-sql-tagged-template-literals-syntax-only

The regular one checks the SQL syntax and assumes any template expression lile `${table_name}` is sent to postgres as a parameter like `$1`. And it seems postgres doesn't support parameters for the table name.
