### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by lishine** [frigus02/vscode-sql-tagged-template-literals#5]
Hello,
How would we add formatting of multi-line sql tagged template literals?

**Comment by frigus02** [comment]
Hi. For some reason I missed your comment. That's related to https://github.com/frigus02/typescript-sql-tagged-template-plugin/issues/4.

**Comment by frigus02** [comment]
I just uploaded extension version 0.0.16, which supports formatting. See changelog for more details:

https://github.com/frigus02/vscode-sql-tagged-template-literals/blob/master/extension/CHANGELOG.md#0014---2020-10-21
